cmake_minimum_required(VERSION 3.29)
project(PROJEKT_ZOO)

set(CMAKE_CXX_STANDARD 20)

add_executable(PROJEKT_ZOO main.cpp
        Armor.h
        Armor.cpp
        ArmorTile.h
        AxeTile.cpp
        Axe.h
        Axe.cpp
        AxeTile.h
        AxeTile.cpp
        Bush.h
        Bush.cpp
        Campfire.h
        Campfire.cpp
        EnemyFactory.h
        EnemyFactory.cpp
        Exit.h
        Exit.cpp
        GameEngine.h
        GameEngine.cpp
        Goblin.h
        Goblin.cpp
        GoblinLite.h
        GoblinLite.cpp
        GoblinPro.h
        GoblinPro.cpp
        GoblinTile.h
        GoblinTile.cpp
        Ground.h
        Ground.cpp
        Inventory.h
        Inventory.cpp
        Items.h
        Items.cpp
        main.cpp
        Map.h
        Map.cpp
        MapCreator.h
        MapCreator.cpp
        Player.h
        Player.cpp
        Skeleton.h
        Skeleton.cpp
        SkeletonLite.h
        SkeletonLite.cpp
        SkeletonPro.h
        SkeletonPro.cpp
        SkeletonTile.h
        SkeletonTile.cpp
        Sword.h
        Sword.cpp
        SwordTile.h
        SwordTile.cpp
        Tile.h
        Tile.cpp
        Wall.h
        Wall.cpp
        ArmorTile.cpp
        BossTile.cpp
        BossTile.h
        Boss.cpp
        Boss.h
        BossLite.cpp
        BossLite.h
        BossPro.cpp
        BossPro.h
        Potion.cpp
        Potion.h
        PotionTile.cpp
        PotionTile.h
        Sidebar.cpp
        Sidebar.h
)